name: feed_vertical_infinito
description: "Um app mobile em Flutter (Dart) que apresenta um feed de vídeos verticais, no estilo TikTok/Reels, utilizando a rede social Bluesky como backend, via a biblioteca atproto."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  atproto: ^0.13.3
  bluesky: ^0.18.10
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  infinite_scroll_pagination: ^5.0.0
  signals_flutter: ^6.0.2
  video_player: ^2.9.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
